### ISSUE TITLE
Offset OSK location to make it work on round displays

### ISSUE THREAD

**Issue by femski** [cass00/improved-osk-gnome-ext#10]
**Describe the bug**

I am trying to program on a round display like this:
https://www.waveshare.com/5inch-1080x1080-lcd.htm

**To Reproduce**

As you can imagine since OSK shows up on absolute bottom of the screen, keys on bottom left and bottom right are off the screen. It could work if the keyboard could be shifted up slightly. Is there a way to do that?

**Comment by cass00** [comment]
Probably easiest to use https://github.com/Vishram1123/gjs-osk .
