### ISSUE TITLE
Additional Feature

### ISSUE THREAD

**Issue by radiolaria81** [cass00/improved-osk-gnome-ext#13]
Hello, i am missing a really important feature. can you please integrate an option to make the osk "always visible"? Or is this even possible? Btw, u did good work and thanks a lot!

kind regards
radiolaria

**Comment by cass00** [comment]
I do not consider this to be an important feature. You could patch the close function to do nothing:

```
this._injectionManager.overrideMethod(
  Keyboard.Keyboard.prototype, 'close',
  originalMethod => {
    return function (...args) {
      return;
    }
  });
```
But this might have some side effects.
