### ISSUE TITLE
Pressing delete doesn't work in most cases in the Wayland session.

### ISSUE THREAD

**Issue by houssemko** [cass00/improved-osk-gnome-ext#4]
**Describe the bug**
Using the Wayland session , When you press delete button the last character written isn't deleted but sometimes selected .

**Expected behavior**
Pressing delete deletes the last written character .

**Environment (please complete the following information):**
 - Distro: [Arch]
 - Gnome version: [45]

**Comment by cass00** [comment]
I have also seen this happen once. Can you reproduce this consistently? If so, see if it happens with the regular OSK as well. In the latter case, it must be problem in GNOME shell. Note that the delete key action is not modified by the extension.

**Comment by houssemko** [comment]
Yes it happens consistently, the previous improved-osk extension fixed that issue for me on gnome 44 so i thought it's possible to implement the same fix in this fork too .

**Comment by cass00** [comment]
Does it also happen with the normal OSK ?

**Comment by houssemko** [comment]
Yes it does.

**Comment by cass00** [comment]
Are you using Gnome 45.2? There is this [patch](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/96b3d1890ced40edf2062d720638fdcfd95943bd) and improves backspace functionality for me.

**Comment by houssemko** [comment]
yes i'm on Gnome 45.2.

**Comment by houssemko** [comment]
how do I use that patch

**Comment by cass00** [comment]
It's included in 45.2 . You are using it already.

**Comment by houssemko** [comment]
it's not fixed yet for me.

**Comment by cass00** [comment]
Added the delete override again. Shoud be working now again. https://github.com/cass00/enhanced-osk-gnome-ext/commit/db77e7e5ee6366c6654998024a111661ff028163
