### ISSUE TITLE
Extension “improvedosk@stefan_k” does not exist

### ISSUE THREAD

**Issue by femski** [cass00/improved-osk-gnome-ext#5]
**Describe the bug**
Provided instructions do not work to install enable the extension

**To Reproduce**
./package-extension.sh
gnome-extensions install improvedosk@stefan-k.shell-extension.zip
gnome-extensions enable improvedosk@stefan_k

**Expected behavior**
extension is available on re-login

**Screenshots**
Exact errr is:
Extension “improvedosk@stefan_k” does not exist

**Environment (please complete the following information):**
Ubuntu 23.10 on Raspberry Pi

**Additional context**
Have you been running your system for a while, or is it a fresh installation?
Fresh installation 

Are you running any other extensions that might interfere with on-screen keyboard?
No

Does `journalctl /usr/bin/gnome-shell -f -o cat` show any errors?
No

**Comment by neopostmodern** [comment]
Have you tried with `gnome-extensions enable improvedosk@stefan-k` instead of `stefan_k`?

**Comment by robertkirkman** [comment]
I logged out of GNOME after the `install` step and logged back in again and after I did that the last command worked :)  If you are using touchscreen, I recommend going to extention settings in GNOME Tweaks and enabling "force touch input" and "show panel indicator"

![Screenshot from 2023-12-07 17-59-50](https://github.com/cass00/improved-osk-gnome-ext/assets/31490854/3eee1e56-a4e9-4d5b-ab2d-5a45b086ac27)

**Comment by femski** [comment]
Thank you! It seems you published the extension to official location and this has ended all confusion. I was able to install it using extension manager and configure it to be proper height for my widescreen touchscreen (original keyboard was getting cutoff at the bottom)  - its a fabulous extension and thank you for keeping it going!
