### ISSUE TITLE
Installation instruction order

### ISSUE THREAD

**Issue by neopostmodern** [cass00/improved-osk-gnome-ext#6]
I tried following the installation instructions and couldn't `enable` the extension. I then found out that I needed log out and in again before `enable` could work, but not after running `enable`. 

Is this only me (GNOME 45.1 on Manjaro) or is this how it works and the README should be updated?

**Comment by robertkirkman** [comment]
in Ubuntu 23.10 I also had to do exactly that. not only you

**Comment by cass00** [comment]
Fixed
