### ISSUE TITLE
Does not work on PMOS/GNOME Shell mobile

### ISSUE THREAD

**Issue by bellegarde-c** [cass00/improved-osk-gnome-ext#8]
If fails with this error: **this._currentPage.getRatio is not a function**

**Comment by cass00** [comment]
I do not have access to postmarket os or gnome shell mobile, so I won't fix this for the moment.

**Comment by sungsphinx** [comment]
> I do not have access to postmarket os or gnome shell mobile, so I won't fix this for the moment.

@cass00 While I was testing this extension through QEMU (https://wiki.postmarketos.org/wiki/Pmbootstrap, https://wiki.postmarketos.org/wiki/Category:QEMU (choose `gnome-mobile` for the `User interface` option)), I have a different error:

```
layout._rows[index_row].keys[i] is undefined
```
